# Generated by Django 5.2.4 on 2025-09-03 16:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP addresses to block', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='when this IP was blocked')),
                ('reason', models.CharField(blank=True, help_text='why this IP was blocked', max_length=250)),
            ],
            options={
                'verbose_name': 'Blocked IP',
                'verbose_name_plural': 'Blocked IPs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuspiciousIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address showing suspicious behavior')),
                ('reason', models.CharField(help_text='Specific suspicious behavior detected', max_length=250)),
                ('detected_at', models.DateTimeField(auto_now_add=True, help_text='When suspicious activity was detected')),
            ],
            options={
                'verbose_name': 'Suspicious IP',
                'verbose_name_plural': 'Suspicious IPs',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='Client IP address')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='when the request was made')),
                ('path', models.CharField(help_text='requested url path', max_length=500)),
            ],
            options={
                'verbose_name': 'Request Log',
                'verbose_name_plural': 'Request Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ip_address'], name='idx_request_ip'), models.Index(fields=['timestamp'], name='idx_request_time'), models.Index(fields=['ip_address', 'timestamp'], name='idx_ip_time')],
            },
        ),
    ]
