# Generated by Django 5.2.4 on 2025-09-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='city',
            field=models.CharField(blank=True, help_text='City the IP originates from', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='country',
            field=models.CharField(blank=True, help_text='Country the IP originates from', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='country_code',
            field=models.CharField(blank=True, help_text='Country code (KE, US, GB)', max_length=2, null=True),
        ),
    ]
